name: do-the-job
on: 
  pull_request:
    paths:
      - projects/**
env: 
  TF_VERSION: 1.3.0
  TG_VERSION: 0.37.1      
permissions:
  id-token: write
  contents: read
jobs:
  start-runner:
    name: Start-EC2-Runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::174566636641:role/OIDC_SELF_HOSTED
          role-duration-seconds: 3600
          role-session-name: GitHubOidctestSession
          aws-region: ca-central-1
      - name: start the EC2 Self Hosted Runner
        run: |
          aws ec2 start-instances --instance-ids i-0d143cde43cfb97e1
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

  Connect-to-self-hosted-runner:
    needs: start-runner
    name: Do the Job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check for new account creation
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          diff_relative: "true"
          dir_names: "true"
          files: |
           projects/**/accounts
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run step if any new project-set is created
        if: steps.changed-files-specific.outputs.added_files != ''
        run: |
          for file in ${{ steps.changed-files-specific.outputs.added_files }}; do
            echo "$file was added"
            cd $file
            pwd
            ls
            terraform init --upgrade=true
            terraform plan
            terraform destroy -auto-approve
            cd $(git rev-parse --show-toplevel)
          done

      - name: Check for new layer creation
        id: added-layers-specific
        uses: tj-actions/changed-files@v34
        with:
          diff_relative: "true"
          dir_names: "true"
          files: |
           projects/**
          

      - name: Run step if any new layer in the project-set accounts is added
        if: steps.added-layers-specific.outputs.added_files != '' && !contains(steps.added-layers-specific.outputs.added_files, 'accounts')
        run: |
          for file in ${{ steps.added-layers-specific.outputs.added_files }}; do
            echo "$file was added"
            cd $file
            pwd
            echo $(terragrunt plan)
            cd $(git rev-parse --show-toplevel)
            pwd
          done  
                  
      - name: Check for existing project-set modification
        id: modified-files-specific
        uses: tj-actions/changed-files@v34
        with:
          diff_relative: "true"
          dir_names: "true"
          files: |
           projects/**
      - name: Run step if any file(s) in the existing project-set folder is modified
        if: steps.modified-files-specific.outputs.modified_files != ''
        run: |
          for file in ${{ steps.modified-files-specific.outputs.modified_files }}; do
            echo "$file was modified"
            cd $file
            pwd
            terragrunt run-all plan 
            cd $(git rev-parse --show-toplevel)
          done
  stop-runner:
    if: always()
    needs: [start-runner, Connect-to-self-hosted-runner]
    name: Stop-EC2-Runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::174566636641:role/OIDC_SELF_HOSTED
          role-duration-seconds: 3600
          role-session-name: GitHubOidctestSession
          aws-region: ca-central-1
      - name: stop the EC2 Self Hosted Runner
        run: |
          aws ec2 stop-instances --instance-ids i-0d143cde43cfb97e1