name: CI-PULL

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Hello"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
